# Generated by Django 5.1.2 on 2024-11-03 22:56

import app_5.models.models_factura
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('caja', 'Caja')], max_length=20)),
                ('password', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(choices=[('bebida', 'Bebida'), ('perecedero', 'Perecedero'), ('alimentacion', 'Alimentacion'), ('utilidad', 'Utilidad')], default='Utilidad', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default='efectivo', max_length=8)),
                ('iva', models.BooleanField(default=True, editable=False)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19, editable=False, max_digits=4, validators=[app_5.models.models_factura.validate_iva])),
                ('bebidas', models.BooleanField(default=False)),
                ('impuesto_bebidas', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('otros', models.BooleanField(default=False)),
                ('impuesto_otros', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distribuidor', models.CharField(max_length=50, unique=True)),
                ('rut_distribuidor', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('nombre_item', models.CharField(max_length=100)),
                ('tipo_item', models.CharField(choices=[('unidad', 'Unidad'), ('kilo', 'Kilo')], default='unidad', max_length=6)),
                ('valor_unidad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_kilo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cantidad_item', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'unique_together': {('nombre_item', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_responsable', models.CharField(max_length=50, unique=True)),
                ('rut_persona_responsable', models.CharField(max_length=10, unique=True)),
                ('rut_negocio', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_5.usuario')),
                ('tiempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('app_5.usuario',),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('detalle_factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_5.detalle_factura')),
                ('caja_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caja_factura', to='app_5.caja')),
                ('distribuidor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='distribuidora_factura', to='app_5.distribuidora')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_factura', to='app_5.item')),
                ('negocio_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='negocio_factura', to='app_5.negocio')),
            ],
            bases=('app_5.detalle_factura',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_5.item')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_code', models.ImageField(blank=True, unique=True, upload_to='qr_codes')),
                ('categoria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producto', to='app_5.categoria')),
            ],
            bases=('app_5.item',),
        ),
    ]
